# 所有节点添加的配置
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd

---
# worker join
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: 605l*******************
    apiServerEndpoint: master.k8s.vip.home:6443
    caCertHashes:
    - sha256:84793437585*********************************************