apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-demo-cm
data:
  ROOT_PASSWORD: 'root'
---

#apiVersion: v1
#kind: Secret
#metadata:
#  name: mariadb-demo-cs
#data:
#  name: cm9vdA==  # root
#  pwd: MTIzNDU2   # 123456
#  db: bXlzcWw=    # mysql
#---

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mariadb-demo-pv
#
#spec:
#  storageClassName: hm77-nfs
#  accessModes:
#    - ReadWriteMany
#  capacity:
#    storage: 8Gi
#
#  nfs:
#    path: /mnt/ssd/k8s-cluster/mariadb-test
#    server: truenas-hm77.home
---

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mariadb-demo-pvc
#
#spec:
#  storageClassName: hm77-nfs
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 8Gi
#---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-demo-sts

spec:
  serviceName: mariadb-demo-svc
  replicas: 1

  volumeClaimTemplates:
  - metadata:
      name: mariadb-demo-persistent
    spec:
      storageClassName: hm77-nfs-client
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 8Gi

  selector:
    matchLabels:
      app: mariadb-demo

  template:
    metadata:
      labels:
        app: mariadb-demo
    spec:
      containers:
      - image: mariadb
        name: mariadb-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

        envFrom:
        - prefix: 'MARIADB_'
          configMapRef:
            name: mariadb-demo-cm

        volumeMounts:
        - name: mariadb-demo-persistent
          mountPath: /var/lib/mysql
