apiVersion: v1
kind: Service
metadata:
  namespace: mysql-cluster
  name: mysql-rw-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql-rw-sts
